services:
  postgres:
    image: postgres:17.2-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=rumarkio
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rumarkio_test
